
#
# This file compiles common utility files
#

BUILD_DIR = ../../build
SRC_DIR = ../

# This include the common make file
-include ../common/Makefile-common

$(info = Compiling common source files...)

-include ../common/Makefile-compile-cpp
